/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.ide;


/**
 * Use this class to register ide components.
 */
public class GlobalJadeIdeModule extends AbstractGlobalJadeIdeModule {
}
