/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.globaltype.globaljade.GlobalJadeRuntimeModule;
import org.xtext.globaltype.globaljade.GlobalJadeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GlobalJadeIdeSetup extends GlobalJadeStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GlobalJadeRuntimeModule(), new GlobalJadeIdeModule()));
	}
	
}
