/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.globaltype.globaljade.parser.antlr.internal.InternalGlobalJadeParser;
import org.xtext.globaltype.globaljade.services.GlobalJadeGrammarAccess;

public class GlobalJadeParser extends AbstractAntlrParser {

	@Inject
	private GlobalJadeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGlobalJadeParser createParser(XtextTokenStream stream) {
		return new InternalGlobalJadeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public GlobalJadeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GlobalJadeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
