/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GlobalJadeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/globaltype/globaljade/parser/antlr/internal/InternalGlobalJade.tokens");
	}
}
