/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GlobalJadeUiModule extends AbstractGlobalJadeUiModule {

	public GlobalJadeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
