/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GlobalJadeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGlobalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cProtocolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameGENERAL_NAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRolesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRolesRoleParserRuleCall_4_0 = (RuleCall)cRolesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cRolesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRolesRoleParserRuleCall_5_1_0 = (RuleCall)cRolesAssignment_5_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cProtocolAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cProtocolProtocolParserRuleCall_8_0 = (RuleCall)cProtocolAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		///*
		// * file extension: gbjade
		// */
		//Model:
		//    // global protocol declaration
		//    'global' 'protocol' name=GENERAL_NAME '(' roles+=Role (',' roles+=Role)*')'
		//    '{'
		//        protocol+=Protocol
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//// global protocol declaration
		//'global' 'protocol' name=GENERAL_NAME '(' roles+=Role (',' roles+=Role)*')'
		//'{'
		//    protocol+=Protocol
		//'}'
		public Group getGroup() { return cGroup; }
		
		//// global protocol declaration
		//'global'
		public Keyword getGlobalKeyword_0() { return cGlobalKeyword_0; }
		
		//'protocol'
		public Keyword getProtocolKeyword_1() { return cProtocolKeyword_1; }
		
		//name=GENERAL_NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//GENERAL_NAME
		public RuleCall getNameGENERAL_NAMETerminalRuleCall_2_0() { return cNameGENERAL_NAMETerminalRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//roles+=Role
		public Assignment getRolesAssignment_4() { return cRolesAssignment_4; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_4_0() { return cRolesRoleParserRuleCall_4_0; }
		
		//(',' roles+=Role)*
		public Group getGroup_5() { return cGroup_5; }
		
		//','
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//roles+=Role
		public Assignment getRolesAssignment_5_1() { return cRolesAssignment_5_1; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_5_1_0() { return cRolesRoleParserRuleCall_5_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//protocol+=Protocol
		public Assignment getProtocolAssignment_8() { return cProtocolAssignment_8; }
		
		//Protocol
		public RuleCall getProtocolProtocolParserRuleCall_8_0() { return cProtocolProtocolParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ProtocolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Protocol");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProtocolAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cActionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cActionsAlternatives_1_0 = (Alternatives)cActionsAssignment_1.eContents().get(0);
		private final RuleCall cActionsMessageParserRuleCall_1_0_0 = (RuleCall)cActionsAlternatives_1_0.eContents().get(0);
		private final RuleCall cActionsChoice_ruleParserRuleCall_1_0_1 = (RuleCall)cActionsAlternatives_1_0.eContents().get(1);
		private final RuleCall cActionsFor_loopParserRuleCall_1_0_2 = (RuleCall)cActionsAlternatives_1_0.eContents().get(2);
		private final RuleCall cActionsEnd_messageParserRuleCall_1_0_3 = (RuleCall)cActionsAlternatives_1_0.eContents().get(3);
		private final RuleCall cActionsRecursionParserRuleCall_1_0_4 = (RuleCall)cActionsAlternatives_1_0.eContents().get(4);
		private final RuleCall cActionsEnd_RecursionParserRuleCall_1_0_5 = (RuleCall)cActionsAlternatives_1_0.eContents().get(5);
		private final RuleCall cActionsContinue_RecursionParserRuleCall_1_0_6 = (RuleCall)cActionsAlternatives_1_0.eContents().get(6);
		
		//Protocol:
		//    {Protocol} (actions+=(Message
		//               | Choice_rule
		//               | For_loop
		//               | End_message
		//               | Recursion
		//               | End_Recursion
		//               | Continue_Recursion
		//               ))*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Protocol} (actions+=(Message
		//           | Choice_rule
		//           | For_loop
		//           | End_message
		//           | Recursion
		//           | End_Recursion
		//           | Continue_Recursion
		//           ))*
		public Group getGroup() { return cGroup; }
		
		//{Protocol}
		public Action getProtocolAction_0() { return cProtocolAction_0; }
		
		//(actions+=(Message
		//              | Choice_rule
		//              | For_loop
		//              | End_message
		//              | Recursion
		//              | End_Recursion
		//              | Continue_Recursion
		//              ))*
		public Assignment getActionsAssignment_1() { return cActionsAssignment_1; }
		
		//(Message
		//               | Choice_rule
		//               | For_loop
		//               | End_message
		//               | Recursion
		//               | End_Recursion
		//               | Continue_Recursion
		//               )
		public Alternatives getActionsAlternatives_1_0() { return cActionsAlternatives_1_0; }
		
		//Message
		public RuleCall getActionsMessageParserRuleCall_1_0_0() { return cActionsMessageParserRuleCall_1_0_0; }
		
		//Choice_rule
		public RuleCall getActionsChoice_ruleParserRuleCall_1_0_1() { return cActionsChoice_ruleParserRuleCall_1_0_1; }
		
		//For_loop
		public RuleCall getActionsFor_loopParserRuleCall_1_0_2() { return cActionsFor_loopParserRuleCall_1_0_2; }
		
		//End_message
		public RuleCall getActionsEnd_messageParserRuleCall_1_0_3() { return cActionsEnd_messageParserRuleCall_1_0_3; }
		
		//Recursion
		public RuleCall getActionsRecursionParserRuleCall_1_0_4() { return cActionsRecursionParserRuleCall_1_0_4; }
		
		//End_Recursion
		public RuleCall getActionsEnd_RecursionParserRuleCall_1_0_5() { return cActionsEnd_RecursionParserRuleCall_1_0_5; }
		
		//Continue_Recursion
		public RuleCall getActionsContinue_RecursionParserRuleCall_1_0_6() { return cActionsContinue_RecursionParserRuleCall_1_0_6; }
	}
	public class RecursionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Recursion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRecKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameGENERAL_NAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Recursion:
		//    'rec' name=GENERAL_NAME ':'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'rec' name=GENERAL_NAME ':'
		public Group getGroup() { return cGroup; }
		
		//'rec'
		public Keyword getRecKeyword_0() { return cRecKeyword_0; }
		
		//name=GENERAL_NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//GENERAL_NAME
		public RuleCall getNameGENERAL_NAMETerminalRuleCall_1_0() { return cNameGENERAL_NAMETerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
	}
	public class End_RecursionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.End_Recursion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameGENERAL_NAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//End_Recursion:
		//    'stop' name=GENERAL_NAME
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'stop' name=GENERAL_NAME
		public Group getGroup() { return cGroup; }
		
		//'stop'
		public Keyword getStopKeyword_0() { return cStopKeyword_0; }
		
		//name=GENERAL_NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//GENERAL_NAME
		public RuleCall getNameGENERAL_NAMETerminalRuleCall_1_0() { return cNameGENERAL_NAMETerminalRuleCall_1_0; }
	}
	public class Continue_RecursionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Continue_Recursion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContinueKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameGENERAL_NAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Continue_Recursion:
		//    'continue' name=GENERAL_NAME
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'continue' name=GENERAL_NAME
		public Group getGroup() { return cGroup; }
		
		//'continue'
		public Keyword getContinueKeyword_0() { return cContinueKeyword_0; }
		
		//name=GENERAL_NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//GENERAL_NAME
		public RuleCall getNameGENERAL_NAMETerminalRuleCall_1_0() { return cNameGENERAL_NAMETerminalRuleCall_1_0; }
	}
	public class Choice_ruleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Choice_rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAtKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRole_nameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRole_nameGENERAL_NAMETerminalRuleCall_2_0 = (RuleCall)cRole_nameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBranchAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBranchProtocolParserRuleCall_4_0 = (RuleCall)cBranchAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cOrKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cBranchAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cBranchProtocolParserRuleCall_6_2_0 = (RuleCall)cBranchAssignment_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		
		//Choice_rule:
		//    // for choice
		//    'choice' 'at' role_name=GENERAL_NAME '{'
		//        //messages+=Message*
		//        branch+=Protocol
		//    '}' ('or' '{'
		//        //messages+=Message*
		//        branch+=Protocol
		//    '}')*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//// for choice
		//'choice' 'at' role_name=GENERAL_NAME '{'
		//    //messages+=Message*
		//    branch+=Protocol
		//'}' ('or' '{'
		//    //messages+=Message*
		//    branch+=Protocol
		//'}')*
		public Group getGroup() { return cGroup; }
		
		//// for choice
		//'choice'
		public Keyword getChoiceKeyword_0() { return cChoiceKeyword_0; }
		
		//'at'
		public Keyword getAtKeyword_1() { return cAtKeyword_1; }
		
		//role_name=GENERAL_NAME
		public Assignment getRole_nameAssignment_2() { return cRole_nameAssignment_2; }
		
		//GENERAL_NAME
		public RuleCall getRole_nameGENERAL_NAMETerminalRuleCall_2_0() { return cRole_nameGENERAL_NAMETerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		////messages+=Message*
		//branch+=Protocol
		public Assignment getBranchAssignment_4() { return cBranchAssignment_4; }
		
		//Protocol
		public RuleCall getBranchProtocolParserRuleCall_4_0() { return cBranchProtocolParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
		
		//('or' '{'
		//       //messages+=Message*
		//       branch+=Protocol
		//   '}')*
		public Group getGroup_6() { return cGroup_6; }
		
		//'or'
		public Keyword getOrKeyword_6_0() { return cOrKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		////messages+=Message*
		//branch+=Protocol
		public Assignment getBranchAssignment_6_2() { return cBranchAssignment_6_2; }
		
		//Protocol
		public RuleCall getBranchProtocolParserRuleCall_6_2_0() { return cBranchProtocolParserRuleCall_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_3() { return cRightCurlyBracketKeyword_6_3; }
	}
	public class For_loopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.For_loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameGENERAL_NAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRoleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRoleGENERAL_NAMETerminalRuleCall_3_0 = (RuleCall)cRoleAssignment_3.eContents().get(0);
		private final Keyword cDoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBranchAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBranchProtocolParserRuleCall_6_0 = (RuleCall)cBranchAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//For_loop:
		//    'forall' name=GENERAL_NAME 'in' role=GENERAL_NAME 'do' '{'
		//        (
		//            branch+=Protocol
		//        )
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'forall' name=GENERAL_NAME 'in' role=GENERAL_NAME 'do' '{'
		//    (
		//        branch+=Protocol
		//    )
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'forall'
		public Keyword getForallKeyword_0() { return cForallKeyword_0; }
		
		//name=GENERAL_NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//GENERAL_NAME
		public RuleCall getNameGENERAL_NAMETerminalRuleCall_1_0() { return cNameGENERAL_NAMETerminalRuleCall_1_0; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//role=GENERAL_NAME
		public Assignment getRoleAssignment_3() { return cRoleAssignment_3; }
		
		//GENERAL_NAME
		public RuleCall getRoleGENERAL_NAMETerminalRuleCall_3_0() { return cRoleGENERAL_NAMETerminalRuleCall_3_0; }
		
		//'do'
		public Keyword getDoKeyword_4() { return cDoKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//(
		//    branch+=Protocol
		//)
		public Assignment getBranchAssignment_6() { return cBranchAssignment_6; }
		
		//Protocol
		public RuleCall getBranchProtocolParserRuleCall_6_0() { return cBranchProtocolParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class End_messageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.End_message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEndAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cEndEND_MEXParserRuleCall_0_0 = (RuleCall)cEndAssignment_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//End_message:
		//    end+=END_MEX ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//end+=END_MEX ';'
		public Group getGroup() { return cGroup; }
		
		//end+=END_MEX
		public Assignment getEndAssignment_0() { return cEndAssignment_0; }
		
		//END_MEX
		public RuleCall getEndEND_MEXParserRuleCall_0_0() { return cEndEND_MEXParserRuleCall_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class END_MEXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.END_MEX");
		private final Keyword cEndKeyword = (Keyword)rule.eContents().get(1);
		
		//END_MEX:
		//    'end'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'end'
		public Keyword getEndKeyword() { return cEndKeyword; }
	}
	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTYPE_MESSAGETerminalRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cContentAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cContentCONTENTTerminalRuleCall_2_0 = (RuleCall)cContentAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cContentAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cContentCONTENTTerminalRuleCall_3_1_0 = (RuleCall)cContentAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cFromKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRoleAAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRoleAGENERAL_NAMETerminalRuleCall_6_0 = (RuleCall)cRoleAAssignment_6.eContents().get(0);
		private final Keyword cToKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cRoleBAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cRoleBGENERAL_NAMETerminalRuleCall_8_0 = (RuleCall)cRoleBAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Message:
		//    type=TYPE_MESSAGE '('content+=CONTENT (',' content+=CONTENT)*')' 'from' roleA=GENERAL_NAME 'to' roleB=GENERAL_NAME ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//type=TYPE_MESSAGE '('content+=CONTENT (',' content+=CONTENT)*')' 'from' roleA=GENERAL_NAME 'to' roleB=GENERAL_NAME ';'
		public Group getGroup() { return cGroup; }
		
		//type=TYPE_MESSAGE
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//TYPE_MESSAGE
		public RuleCall getTypeTYPE_MESSAGETerminalRuleCall_0_0() { return cTypeTYPE_MESSAGETerminalRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//content+=CONTENT
		public Assignment getContentAssignment_2() { return cContentAssignment_2; }
		
		//CONTENT
		public RuleCall getContentCONTENTTerminalRuleCall_2_0() { return cContentCONTENTTerminalRuleCall_2_0; }
		
		//(',' content+=CONTENT)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//content+=CONTENT
		public Assignment getContentAssignment_3_1() { return cContentAssignment_3_1; }
		
		//CONTENT
		public RuleCall getContentCONTENTTerminalRuleCall_3_1_0() { return cContentCONTENTTerminalRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'from'
		public Keyword getFromKeyword_5() { return cFromKeyword_5; }
		
		//roleA=GENERAL_NAME
		public Assignment getRoleAAssignment_6() { return cRoleAAssignment_6; }
		
		//GENERAL_NAME
		public RuleCall getRoleAGENERAL_NAMETerminalRuleCall_6_0() { return cRoleAGENERAL_NAMETerminalRuleCall_6_0; }
		
		//'to'
		public Keyword getToKeyword_7() { return cToKeyword_7; }
		
		//roleB=GENERAL_NAME
		public Assignment getRoleBAssignment_8() { return cRoleBAssignment_8; }
		
		//GENERAL_NAME
		public RuleCall getRoleBGENERAL_NAMETerminalRuleCall_8_0() { return cRoleBGENERAL_NAMETerminalRuleCall_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRoleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRoleGENERAL_NAMETerminalRuleCall_1_0 = (RuleCall)cRoleAssignment_1.eContents().get(0);
		
		//Role:
		//    'role' role=GENERAL_NAME // dovrei mettere la parte opzionale per quanto riguarda piu' ruoli
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'role' role=GENERAL_NAME
		public Group getGroup() { return cGroup; }
		
		//'role'
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }
		
		//role=GENERAL_NAME
		public Assignment getRoleAssignment_1() { return cRoleAssignment_1; }
		
		//GENERAL_NAME
		public RuleCall getRoleGENERAL_NAMETerminalRuleCall_1_0() { return cRoleGENERAL_NAMETerminalRuleCall_1_0; }
	}
	
	
	private final ModelElements pModel;
	private final ProtocolElements pProtocol;
	private final RecursionElements pRecursion;
	private final End_RecursionElements pEnd_Recursion;
	private final Continue_RecursionElements pContinue_Recursion;
	private final Choice_ruleElements pChoice_rule;
	private final For_loopElements pFor_loop;
	private final End_messageElements pEnd_message;
	private final END_MEXElements pEND_MEX;
	private final MessageElements pMessage;
	private final TerminalRule tTYPE_MESSAGE;
	private final TerminalRule tCONTENT;
	private final RoleElements pRole;
	private final TerminalRule tGENERAL_NAME;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GlobalJadeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pProtocol = new ProtocolElements();
		this.pRecursion = new RecursionElements();
		this.pEnd_Recursion = new End_RecursionElements();
		this.pContinue_Recursion = new Continue_RecursionElements();
		this.pChoice_rule = new Choice_ruleElements();
		this.pFor_loop = new For_loopElements();
		this.pEnd_message = new End_messageElements();
		this.pEND_MEX = new END_MEXElements();
		this.pMessage = new MessageElements();
		this.tTYPE_MESSAGE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.TYPE_MESSAGE");
		this.tCONTENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.CONTENT");
		this.pRole = new RoleElements();
		this.tGENERAL_NAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.GENERAL_NAME");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.globaltype.globaljade.GlobalJade".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*
	// * file extension: gbjade
	// */
	//Model:
	//    // global protocol declaration
	//    'global' 'protocol' name=GENERAL_NAME '(' roles+=Role (',' roles+=Role)*')'
	//    '{'
	//        protocol+=Protocol
	//    '}'
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Protocol:
	//    {Protocol} (actions+=(Message
	//               | Choice_rule
	//               | For_loop
	//               | End_message
	//               | Recursion
	//               | End_Recursion
	//               | Continue_Recursion
	//               ))*
	//;
	public ProtocolElements getProtocolAccess() {
		return pProtocol;
	}
	
	public ParserRule getProtocolRule() {
		return getProtocolAccess().getRule();
	}
	
	//Recursion:
	//    'rec' name=GENERAL_NAME ':'
	//;
	public RecursionElements getRecursionAccess() {
		return pRecursion;
	}
	
	public ParserRule getRecursionRule() {
		return getRecursionAccess().getRule();
	}
	
	//End_Recursion:
	//    'stop' name=GENERAL_NAME
	//;
	public End_RecursionElements getEnd_RecursionAccess() {
		return pEnd_Recursion;
	}
	
	public ParserRule getEnd_RecursionRule() {
		return getEnd_RecursionAccess().getRule();
	}
	
	//Continue_Recursion:
	//    'continue' name=GENERAL_NAME
	//;
	public Continue_RecursionElements getContinue_RecursionAccess() {
		return pContinue_Recursion;
	}
	
	public ParserRule getContinue_RecursionRule() {
		return getContinue_RecursionAccess().getRule();
	}
	
	//Choice_rule:
	//    // for choice
	//    'choice' 'at' role_name=GENERAL_NAME '{'
	//        //messages+=Message*
	//        branch+=Protocol
	//    '}' ('or' '{'
	//        //messages+=Message*
	//        branch+=Protocol
	//    '}')*
	//;
	public Choice_ruleElements getChoice_ruleAccess() {
		return pChoice_rule;
	}
	
	public ParserRule getChoice_ruleRule() {
		return getChoice_ruleAccess().getRule();
	}
	
	//For_loop:
	//    'forall' name=GENERAL_NAME 'in' role=GENERAL_NAME 'do' '{'
	//        (
	//            branch+=Protocol
	//        )
	//    '}'
	//;
	public For_loopElements getFor_loopAccess() {
		return pFor_loop;
	}
	
	public ParserRule getFor_loopRule() {
		return getFor_loopAccess().getRule();
	}
	
	//End_message:
	//    end+=END_MEX ';'
	//;
	public End_messageElements getEnd_messageAccess() {
		return pEnd_message;
	}
	
	public ParserRule getEnd_messageRule() {
		return getEnd_messageAccess().getRule();
	}
	
	//END_MEX:
	//    'end'
	//;
	public END_MEXElements getEND_MEXAccess() {
		return pEND_MEX;
	}
	
	public ParserRule getEND_MEXRule() {
		return getEND_MEXAccess().getRule();
	}
	
	//Message:
	//    type=TYPE_MESSAGE '('content+=CONTENT (',' content+=CONTENT)*')' 'from' roleA=GENERAL_NAME 'to' roleB=GENERAL_NAME ';'
	//;
	public MessageElements getMessageAccess() {
		return pMessage;
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}
	
	//terminal TYPE_MESSAGE:
	//    'CFP' | 'REJECT-PROPOSAL' | 'ACCEPT-PROPOSAL' | 'FAILURE' | 'INFORM-DONE' | 'INFORM'
	//;
	public TerminalRule getTYPE_MESSAGERule() {
		return tTYPE_MESSAGE;
	}
	
	//terminal CONTENT:
	//    'int' | 'bool' | 'string'
	//;
	public TerminalRule getCONTENTRule() {
		return tCONTENT;
	}
	
	//Role:
	//    'role' role=GENERAL_NAME // dovrei mettere la parte opzionale per quanto riguarda piu' ruoli
	//;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//terminal GENERAL_NAME:
	//    ('A'..'Z')+ ('a'..'z')*
	//;
	public TerminalRule getGENERAL_NAMERule() {
		return tGENERAL_NAME;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
