/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GlobalJadeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGlobalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cProtocolKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameNAMETerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRolesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRolesRolesParserRuleCall_4_0 = (RuleCall)cRolesAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cProtocolAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cProtocolProtocolParserRuleCall_7_0 = (RuleCall)cProtocolAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		///*
		// * file extension: gbjade
		// */
		//Model:
		//    // global protocol declaration
		//    'global' 'protocol' name=NAME '(' roles+=Roles ')'
		//    '{'
		//        protocol+=Protocol
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//// global protocol declaration
		//'global' 'protocol' name=NAME '(' roles+=Roles ')'
		//'{'
		//    protocol+=Protocol
		//'}'
		public Group getGroup() { return cGroup; }
		
		//// global protocol declaration
		//'global'
		public Keyword getGlobalKeyword_0() { return cGlobalKeyword_0; }
		
		//'protocol'
		public Keyword getProtocolKeyword_1() { return cProtocolKeyword_1; }
		
		//name=NAME
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_2_0() { return cNameNAMETerminalRuleCall_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//roles+=Roles
		public Assignment getRolesAssignment_4() { return cRolesAssignment_4; }
		
		//Roles
		public RuleCall getRolesRolesParserRuleCall_4_0() { return cRolesRolesParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//protocol+=Protocol
		public Assignment getProtocolAssignment_7() { return cProtocolAssignment_7; }
		
		//Protocol
		public RuleCall getProtocolProtocolParserRuleCall_7_0() { return cProtocolProtocolParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RolesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Roles");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRolesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRolesRoleParserRuleCall_0_0 = (RuleCall)cRolesAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRolesAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRolesRoleParserRuleCall_1_1_0 = (RuleCall)cRolesAssignment_1_1.eContents().get(0);
		
		//Roles:
		//    roles+=Role (',' roles+=Role)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//roles+=Role (',' roles+=Role)*
		public Group getGroup() { return cGroup; }
		
		//roles+=Role
		public Assignment getRolesAssignment_0() { return cRolesAssignment_0; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_0_0() { return cRolesRoleParserRuleCall_0_0; }
		
		//(',' roles+=Role)*
		public Group getGroup_1() { return cGroup_1; }
		
		//','
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }
		
		//roles+=Role
		public Assignment getRolesAssignment_1_1() { return cRolesAssignment_1_1; }
		
		//Role
		public RuleCall getRolesRoleParserRuleCall_1_1_0() { return cRolesRoleParserRuleCall_1_1_0; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Role");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOneRoleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMultipleRoleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Role:
		//    OneRole | MultipleRole
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//OneRole | MultipleRole
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OneRole
		public RuleCall getOneRoleParserRuleCall_0() { return cOneRoleParserRuleCall_0; }
		
		//MultipleRole
		public RuleCall getMultipleRoleParserRuleCall_1() { return cMultipleRoleParserRuleCall_1; }
	}
	public class OneRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.OneRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//OneRole:
		//    'role' name=NAME
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'role' name=NAME
		public Group getGroup() { return cGroup; }
		
		//'role'
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
	}
	public class MultipleRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.MultipleRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMultroleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRefAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cRefOneRoleCrossReference_3_0 = (CrossReference)cRefAssignment_3.eContents().get(0);
		private final RuleCall cRefOneRoleNAMETerminalRuleCall_3_0_1 = (RuleCall)cRefOneRoleCrossReference_3_0.eContents().get(1);
		
		//MultipleRole:
		//    'multrole' name=NAME ':' ref=[OneRole | NAME]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'multrole' name=NAME ':' ref=[OneRole | NAME]
		public Group getGroup() { return cGroup; }
		
		//'multrole'
		public Keyword getMultroleKeyword_0() { return cMultroleKeyword_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//ref=[OneRole | NAME]
		public Assignment getRefAssignment_3() { return cRefAssignment_3; }
		
		//[OneRole | NAME]
		public CrossReference getRefOneRoleCrossReference_3_0() { return cRefOneRoleCrossReference_3_0; }
		
		//NAME
		public RuleCall getRefOneRoleNAMETerminalRuleCall_3_0_1() { return cRefOneRoleNAMETerminalRuleCall_3_0_1; }
	}
	public class ProtocolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Protocol");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProtocolAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cActionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cActionsAlternatives_1_0 = (Alternatives)cActionsAssignment_1.eContents().get(0);
		private final RuleCall cActionsMessageParserRuleCall_1_0_0 = (RuleCall)cActionsAlternatives_1_0.eContents().get(0);
		private final RuleCall cActionsChoice_ruleParserRuleCall_1_0_1 = (RuleCall)cActionsAlternatives_1_0.eContents().get(1);
		private final RuleCall cActionsFor_loopParserRuleCall_1_0_2 = (RuleCall)cActionsAlternatives_1_0.eContents().get(2);
		private final RuleCall cActionsEnd_messageParserRuleCall_1_0_3 = (RuleCall)cActionsAlternatives_1_0.eContents().get(3);
		private final RuleCall cActionsRecursionParserRuleCall_1_0_4 = (RuleCall)cActionsAlternatives_1_0.eContents().get(4);
		private final RuleCall cActionsEnd_RecursionParserRuleCall_1_0_5 = (RuleCall)cActionsAlternatives_1_0.eContents().get(5);
		private final RuleCall cActionsContinue_RecursionParserRuleCall_1_0_6 = (RuleCall)cActionsAlternatives_1_0.eContents().get(6);
		
		//Protocol:
		//    {Protocol} (actions+=(Message
		//               | Choice_rule
		//               | For_loop
		//               | End_message
		//               | Recursion
		//               | End_Recursion
		//               | Continue_Recursion
		//               ))*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Protocol} (actions+=(Message
		//           | Choice_rule
		//           | For_loop
		//           | End_message
		//           | Recursion
		//           | End_Recursion
		//           | Continue_Recursion
		//           ))*
		public Group getGroup() { return cGroup; }
		
		//{Protocol}
		public Action getProtocolAction_0() { return cProtocolAction_0; }
		
		//(actions+=(Message
		//              | Choice_rule
		//              | For_loop
		//              | End_message
		//              | Recursion
		//              | End_Recursion
		//              | Continue_Recursion
		//              ))*
		public Assignment getActionsAssignment_1() { return cActionsAssignment_1; }
		
		//(Message
		//               | Choice_rule
		//               | For_loop
		//               | End_message
		//               | Recursion
		//               | End_Recursion
		//               | Continue_Recursion
		//               )
		public Alternatives getActionsAlternatives_1_0() { return cActionsAlternatives_1_0; }
		
		//Message
		public RuleCall getActionsMessageParserRuleCall_1_0_0() { return cActionsMessageParserRuleCall_1_0_0; }
		
		//Choice_rule
		public RuleCall getActionsChoice_ruleParserRuleCall_1_0_1() { return cActionsChoice_ruleParserRuleCall_1_0_1; }
		
		//For_loop
		public RuleCall getActionsFor_loopParserRuleCall_1_0_2() { return cActionsFor_loopParserRuleCall_1_0_2; }
		
		//End_message
		public RuleCall getActionsEnd_messageParserRuleCall_1_0_3() { return cActionsEnd_messageParserRuleCall_1_0_3; }
		
		//Recursion
		public RuleCall getActionsRecursionParserRuleCall_1_0_4() { return cActionsRecursionParserRuleCall_1_0_4; }
		
		//End_Recursion
		public RuleCall getActionsEnd_RecursionParserRuleCall_1_0_5() { return cActionsEnd_RecursionParserRuleCall_1_0_5; }
		
		//Continue_Recursion
		public RuleCall getActionsContinue_RecursionParserRuleCall_1_0_6() { return cActionsContinue_RecursionParserRuleCall_1_0_6; }
	}
	public class RecursionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Recursion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRecKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Recursion:
		//    'rec' name=NAME ':'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'rec' name=NAME ':'
		public Group getGroup() { return cGroup; }
		
		//'rec'
		public Keyword getRecKeyword_0() { return cRecKeyword_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
	}
	public class End_RecursionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.End_Recursion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//End_Recursion:
		//    'stop' name=NAME
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'stop' name=NAME
		public Group getGroup() { return cGroup; }
		
		//'stop'
		public Keyword getStopKeyword_0() { return cStopKeyword_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
	}
	public class Continue_RecursionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Continue_Recursion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContinueKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Continue_Recursion:
		//    'continue' name=NAME
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'continue' name=NAME
		public Group getGroup() { return cGroup; }
		
		//'continue'
		public Keyword getContinueKeyword_0() { return cContinueKeyword_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
	}
	public class Choice_ruleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Choice_rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAtKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRole_nameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRole_nameNAMETerminalRuleCall_2_0 = (RuleCall)cRole_nameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMessagesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMessagesMessageParserRuleCall_4_0 = (RuleCall)cMessagesAssignment_4.eContents().get(0);
		private final Assignment cBranchAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBranchProtocolParserRuleCall_5_0 = (RuleCall)cBranchAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cOrKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cMessagesAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cMessagesMessageParserRuleCall_7_2_0 = (RuleCall)cMessagesAssignment_7_2.eContents().get(0);
		private final Assignment cBranchAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cBranchProtocolParserRuleCall_7_3_0 = (RuleCall)cBranchAssignment_7_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		
		//Choice_rule:
		//    // for choice
		//    'choice' 'at' role_name=NAME '{'
		//        messages+=Message
		//        branch+=Protocol
		//    '}' ('or' '{'
		//        messages+=Message
		//        branch+=Protocol
		//    '}')*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//// for choice
		//'choice' 'at' role_name=NAME '{'
		//    messages+=Message
		//    branch+=Protocol
		//'}' ('or' '{'
		//    messages+=Message
		//    branch+=Protocol
		//'}')*
		public Group getGroup() { return cGroup; }
		
		//// for choice
		//'choice'
		public Keyword getChoiceKeyword_0() { return cChoiceKeyword_0; }
		
		//'at'
		public Keyword getAtKeyword_1() { return cAtKeyword_1; }
		
		//role_name=NAME
		public Assignment getRole_nameAssignment_2() { return cRole_nameAssignment_2; }
		
		//NAME
		public RuleCall getRole_nameNAMETerminalRuleCall_2_0() { return cRole_nameNAMETerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//messages+=Message
		public Assignment getMessagesAssignment_4() { return cMessagesAssignment_4; }
		
		//Message
		public RuleCall getMessagesMessageParserRuleCall_4_0() { return cMessagesMessageParserRuleCall_4_0; }
		
		//branch+=Protocol
		public Assignment getBranchAssignment_5() { return cBranchAssignment_5; }
		
		//Protocol
		public RuleCall getBranchProtocolParserRuleCall_5_0() { return cBranchProtocolParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//('or' '{'
		//       messages+=Message
		//       branch+=Protocol
		//   '}')*
		public Group getGroup_7() { return cGroup_7; }
		
		//'or'
		public Keyword getOrKeyword_7_0() { return cOrKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//messages+=Message
		public Assignment getMessagesAssignment_7_2() { return cMessagesAssignment_7_2; }
		
		//Message
		public RuleCall getMessagesMessageParserRuleCall_7_2_0() { return cMessagesMessageParserRuleCall_7_2_0; }
		
		//branch+=Protocol
		public Assignment getBranchAssignment_7_3() { return cBranchAssignment_7_3; }
		
		//Protocol
		public RuleCall getBranchProtocolParserRuleCall_7_3_0() { return cBranchProtocolParserRuleCall_7_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
	}
	public class For_loopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.For_loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNAMETerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cInKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRoleTargetAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRoleTargetNAMETerminalRuleCall_3_0 = (RuleCall)cRoleTargetAssignment_3.eContents().get(0);
		private final Keyword cDoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBranchAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBranchProtocolParserRuleCall_6_0 = (RuleCall)cBranchAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//For_loop:
		//    'forall' name=NAME 'in' roleTarget=NAME 'do' '{'
		//        (
		//            branch+=Protocol
		//        )
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'forall' name=NAME 'in' roleTarget=NAME 'do' '{'
		//    (
		//        branch+=Protocol
		//    )
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'forall'
		public Keyword getForallKeyword_0() { return cForallKeyword_0; }
		
		//name=NAME
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//NAME
		public RuleCall getNameNAMETerminalRuleCall_1_0() { return cNameNAMETerminalRuleCall_1_0; }
		
		//'in'
		public Keyword getInKeyword_2() { return cInKeyword_2; }
		
		//roleTarget=NAME
		public Assignment getRoleTargetAssignment_3() { return cRoleTargetAssignment_3; }
		
		//NAME
		public RuleCall getRoleTargetNAMETerminalRuleCall_3_0() { return cRoleTargetNAMETerminalRuleCall_3_0; }
		
		//'do'
		public Keyword getDoKeyword_4() { return cDoKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//(
		//    branch+=Protocol
		//)
		public Assignment getBranchAssignment_6() { return cBranchAssignment_6; }
		
		//Protocol
		public RuleCall getBranchProtocolParserRuleCall_6_0() { return cBranchProtocolParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class End_messageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.End_message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEndAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cEndEND_MEXParserRuleCall_0_0 = (RuleCall)cEndAssignment_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//End_message:
		//    end+=END_MEX ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//end+=END_MEX ';'
		public Group getGroup() { return cGroup; }
		
		//end+=END_MEX
		public Assignment getEndAssignment_0() { return cEndAssignment_0; }
		
		//END_MEX
		public RuleCall getEndEND_MEXParserRuleCall_0_0() { return cEndEND_MEXParserRuleCall_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class END_MEXElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.END_MEX");
		private final Keyword cEndKeyword = (Keyword)rule.eContents().get(1);
		
		//END_MEX:
		//    'end'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'end'
		public Keyword getEndKeyword() { return cEndKeyword; }
	}
	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTYPE_MESSAGETerminalRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cContentAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cContentCONTENTTerminalRuleCall_2_0 = (RuleCall)cContentAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cContentAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cContentCONTENTTerminalRuleCall_3_1_0 = (RuleCall)cContentAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cFromKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSenderAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSenderNAMETerminalRuleCall_6_0 = (RuleCall)cSenderAssignment_6.eContents().get(0);
		private final Keyword cToKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cReceiverAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cReceiverNAMETerminalRuleCall_8_0 = (RuleCall)cReceiverAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Message:
		//    type=TYPE_MESSAGE '('content+=CONTENT (',' content+=CONTENT)*')' 'from' sender=NAME 'to' receiver=NAME ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//type=TYPE_MESSAGE '('content+=CONTENT (',' content+=CONTENT)*')' 'from' sender=NAME 'to' receiver=NAME ';'
		public Group getGroup() { return cGroup; }
		
		//type=TYPE_MESSAGE
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//TYPE_MESSAGE
		public RuleCall getTypeTYPE_MESSAGETerminalRuleCall_0_0() { return cTypeTYPE_MESSAGETerminalRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//content+=CONTENT
		public Assignment getContentAssignment_2() { return cContentAssignment_2; }
		
		//CONTENT
		public RuleCall getContentCONTENTTerminalRuleCall_2_0() { return cContentCONTENTTerminalRuleCall_2_0; }
		
		//(',' content+=CONTENT)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//content+=CONTENT
		public Assignment getContentAssignment_3_1() { return cContentAssignment_3_1; }
		
		//CONTENT
		public RuleCall getContentCONTENTTerminalRuleCall_3_1_0() { return cContentCONTENTTerminalRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'from'
		public Keyword getFromKeyword_5() { return cFromKeyword_5; }
		
		//sender=NAME
		public Assignment getSenderAssignment_6() { return cSenderAssignment_6; }
		
		//NAME
		public RuleCall getSenderNAMETerminalRuleCall_6_0() { return cSenderNAMETerminalRuleCall_6_0; }
		
		//'to'
		public Keyword getToKeyword_7() { return cToKeyword_7; }
		
		//receiver=NAME
		public Assignment getReceiverAssignment_8() { return cReceiverAssignment_8; }
		
		//NAME
		public RuleCall getReceiverNAMETerminalRuleCall_8_0() { return cReceiverNAMETerminalRuleCall_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }
	}
	
	
	private final ModelElements pModel;
	private final RolesElements pRoles;
	private final RoleElements pRole;
	private final OneRoleElements pOneRole;
	private final MultipleRoleElements pMultipleRole;
	private final ProtocolElements pProtocol;
	private final RecursionElements pRecursion;
	private final End_RecursionElements pEnd_Recursion;
	private final Continue_RecursionElements pContinue_Recursion;
	private final Choice_ruleElements pChoice_rule;
	private final For_loopElements pFor_loop;
	private final End_messageElements pEnd_message;
	private final END_MEXElements pEND_MEX;
	private final MessageElements pMessage;
	private final TerminalRule tTYPE_MESSAGE;
	private final TerminalRule tCONTENT;
	private final TerminalRule tNAME;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GlobalJadeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pRoles = new RolesElements();
		this.pRole = new RoleElements();
		this.pOneRole = new OneRoleElements();
		this.pMultipleRole = new MultipleRoleElements();
		this.pProtocol = new ProtocolElements();
		this.pRecursion = new RecursionElements();
		this.pEnd_Recursion = new End_RecursionElements();
		this.pContinue_Recursion = new Continue_RecursionElements();
		this.pChoice_rule = new Choice_ruleElements();
		this.pFor_loop = new For_loopElements();
		this.pEnd_message = new End_messageElements();
		this.pEND_MEX = new END_MEXElements();
		this.pMessage = new MessageElements();
		this.tTYPE_MESSAGE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.TYPE_MESSAGE");
		this.tCONTENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.CONTENT");
		this.tNAME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.globaltype.globaljade.GlobalJade.NAME");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.globaltype.globaljade.GlobalJade".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*
	// * file extension: gbjade
	// */
	//Model:
	//    // global protocol declaration
	//    'global' 'protocol' name=NAME '(' roles+=Roles ')'
	//    '{'
	//        protocol+=Protocol
	//    '}'
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Roles:
	//    roles+=Role (',' roles+=Role)*
	//;
	public RolesElements getRolesAccess() {
		return pRoles;
	}
	
	public ParserRule getRolesRule() {
		return getRolesAccess().getRule();
	}
	
	//Role:
	//    OneRole | MultipleRole
	//;
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//OneRole:
	//    'role' name=NAME
	//;
	public OneRoleElements getOneRoleAccess() {
		return pOneRole;
	}
	
	public ParserRule getOneRoleRule() {
		return getOneRoleAccess().getRule();
	}
	
	//MultipleRole:
	//    'multrole' name=NAME ':' ref=[OneRole | NAME]
	//;
	public MultipleRoleElements getMultipleRoleAccess() {
		return pMultipleRole;
	}
	
	public ParserRule getMultipleRoleRule() {
		return getMultipleRoleAccess().getRule();
	}
	
	//Protocol:
	//    {Protocol} (actions+=(Message
	//               | Choice_rule
	//               | For_loop
	//               | End_message
	//               | Recursion
	//               | End_Recursion
	//               | Continue_Recursion
	//               ))*
	//;
	public ProtocolElements getProtocolAccess() {
		return pProtocol;
	}
	
	public ParserRule getProtocolRule() {
		return getProtocolAccess().getRule();
	}
	
	//Recursion:
	//    'rec' name=NAME ':'
	//;
	public RecursionElements getRecursionAccess() {
		return pRecursion;
	}
	
	public ParserRule getRecursionRule() {
		return getRecursionAccess().getRule();
	}
	
	//End_Recursion:
	//    'stop' name=NAME
	//;
	public End_RecursionElements getEnd_RecursionAccess() {
		return pEnd_Recursion;
	}
	
	public ParserRule getEnd_RecursionRule() {
		return getEnd_RecursionAccess().getRule();
	}
	
	//Continue_Recursion:
	//    'continue' name=NAME
	//;
	public Continue_RecursionElements getContinue_RecursionAccess() {
		return pContinue_Recursion;
	}
	
	public ParserRule getContinue_RecursionRule() {
		return getContinue_RecursionAccess().getRule();
	}
	
	//Choice_rule:
	//    // for choice
	//    'choice' 'at' role_name=NAME '{'
	//        messages+=Message
	//        branch+=Protocol
	//    '}' ('or' '{'
	//        messages+=Message
	//        branch+=Protocol
	//    '}')*
	//;
	public Choice_ruleElements getChoice_ruleAccess() {
		return pChoice_rule;
	}
	
	public ParserRule getChoice_ruleRule() {
		return getChoice_ruleAccess().getRule();
	}
	
	//For_loop:
	//    'forall' name=NAME 'in' roleTarget=NAME 'do' '{'
	//        (
	//            branch+=Protocol
	//        )
	//    '}'
	//;
	public For_loopElements getFor_loopAccess() {
		return pFor_loop;
	}
	
	public ParserRule getFor_loopRule() {
		return getFor_loopAccess().getRule();
	}
	
	//End_message:
	//    end+=END_MEX ';'
	//;
	public End_messageElements getEnd_messageAccess() {
		return pEnd_message;
	}
	
	public ParserRule getEnd_messageRule() {
		return getEnd_messageAccess().getRule();
	}
	
	//END_MEX:
	//    'end'
	//;
	public END_MEXElements getEND_MEXAccess() {
		return pEND_MEX;
	}
	
	public ParserRule getEND_MEXRule() {
		return getEND_MEXAccess().getRule();
	}
	
	//Message:
	//    type=TYPE_MESSAGE '('content+=CONTENT (',' content+=CONTENT)*')' 'from' sender=NAME 'to' receiver=NAME ';'
	//;
	public MessageElements getMessageAccess() {
		return pMessage;
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}
	
	//terminal TYPE_MESSAGE:
	//    'CFP'
	//    | 'REJECT-PROPOSAL'
	//    | 'ACCEPT-PROPOSAL'
	//    | 'FAILURE'
	//    | 'INFORM-DONE'
	//    | 'INFORM'
	//    | 'PROPOSE'
	//;
	public TerminalRule getTYPE_MESSAGERule() {
		return tTYPE_MESSAGE;
	}
	
	//terminal CONTENT:
	//    'int' | 'bool' | 'string'
	//;
	public TerminalRule getCONTENTRule() {
		return tCONTENT;
	}
	
	//terminal NAME:
	//    ('A'..'Z')+ ('a'..'z')*
	//;
	public TerminalRule getNAMERule() {
		return tNAME;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
