/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.globaltype.globaljade.ide.contentassist.antlr.internal.InternalGlobalJadeParser;
import org.xtext.globaltype.globaljade.services.GlobalJadeGrammarAccess;

public class GlobalJadeParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GlobalJadeGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GlobalJadeGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getProtocolAccess().getActionsAlternatives_1_0(), "rule__Protocol__ActionsAlternatives_1_0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_5(), "rule__Model__Group_5__0");
			builder.put(grammarAccess.getProtocolAccess().getGroup(), "rule__Protocol__Group__0");
			builder.put(grammarAccess.getChoice_ruleAccess().getGroup(), "rule__Choice_rule__Group__0");
			builder.put(grammarAccess.getChoice_ruleAccess().getGroup_6(), "rule__Choice_rule__Group_6__0");
			builder.put(grammarAccess.getFor_loopAccess().getGroup(), "rule__For_loop__Group__0");
			builder.put(grammarAccess.getEnd_messageAccess().getGroup(), "rule__End_message__Group__0");
			builder.put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
			builder.put(grammarAccess.getMessageAccess().getGroup_3(), "rule__Message__Group_3__0");
			builder.put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
			builder.put(grammarAccess.getModelAccess().getRolesAssignment_4(), "rule__Model__RolesAssignment_4");
			builder.put(grammarAccess.getModelAccess().getRolesAssignment_5_1(), "rule__Model__RolesAssignment_5_1");
			builder.put(grammarAccess.getModelAccess().getProtocolAssignment_8(), "rule__Model__ProtocolAssignment_8");
			builder.put(grammarAccess.getProtocolAccess().getActionsAssignment_1(), "rule__Protocol__ActionsAssignment_1");
			builder.put(grammarAccess.getChoice_ruleAccess().getRole_nameAssignment_2(), "rule__Choice_rule__Role_nameAssignment_2");
			builder.put(grammarAccess.getChoice_ruleAccess().getMessagesAssignment_4(), "rule__Choice_rule__MessagesAssignment_4");
			builder.put(grammarAccess.getChoice_ruleAccess().getMessagesAssignment_6_2(), "rule__Choice_rule__MessagesAssignment_6_2");
			builder.put(grammarAccess.getFor_loopAccess().getNameAssignment_1(), "rule__For_loop__NameAssignment_1");
			builder.put(grammarAccess.getFor_loopAccess().getRoleAssignment_3(), "rule__For_loop__RoleAssignment_3");
			builder.put(grammarAccess.getFor_loopAccess().getMessagesAssignment_6(), "rule__For_loop__MessagesAssignment_6");
			builder.put(grammarAccess.getEnd_messageAccess().getEndAssignment_0(), "rule__End_message__EndAssignment_0");
			builder.put(grammarAccess.getMessageAccess().getTypeAssignment_0(), "rule__Message__TypeAssignment_0");
			builder.put(grammarAccess.getMessageAccess().getContentAssignment_2(), "rule__Message__ContentAssignment_2");
			builder.put(grammarAccess.getMessageAccess().getContentAssignment_3_1(), "rule__Message__ContentAssignment_3_1");
			builder.put(grammarAccess.getMessageAccess().getRoleAAssignment_6(), "rule__Message__RoleAAssignment_6");
			builder.put(grammarAccess.getMessageAccess().getRoleBAssignment_8(), "rule__Message__RoleBAssignment_8");
			builder.put(grammarAccess.getRoleAccess().getRoleAssignment_1(), "rule__Role__RoleAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GlobalJadeGrammarAccess grammarAccess;

	@Override
	protected InternalGlobalJadeParser createParser() {
		InternalGlobalJadeParser result = new InternalGlobalJadeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GlobalJadeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GlobalJadeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
