/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGlobalJadeScopeProvider extends DelegatingScopeProvider {
}
