/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadeFactory
 * @model kind="package"
 * @generated
 */
public interface GlobalJadePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "globalJade";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/globaltype/globaljade/GlobalJade";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "globalJade";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GlobalJadePackage eINSTANCE = org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.globaltype.globaljade.globalJade.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globaltype.globaljade.globalJade.impl.ModelImpl
   * @see org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Protocols</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROTOCOLS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globaltype.globaljade.globalJade.impl.ProtocolsImpl <em>Protocols</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globaltype.globaljade.globalJade.impl.ProtocolsImpl
   * @see org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl#getProtocols()
   * @generated
   */
  int PROTOCOLS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOLS__NAME = 0;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOLS__ROLES = 1;

  /**
   * The number of structural features of the '<em>Protocols</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOLS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.globaltype.globaljade.globalJade.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globaltype.globaljade.globalJade.impl.RoleImpl
   * @see org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl#getRole()
   * @generated
   */
  int ROLE = 2;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__ROLE = 0;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.globaltype.globaljade.globalJade.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globaltype.globaljade.globalJade.Model#getProtocols <em>Protocols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Protocols</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Model#getProtocols()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Protocols();

  /**
   * Returns the meta object for class '{@link org.xtext.globaltype.globaljade.globalJade.Protocols <em>Protocols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protocols</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Protocols
   * @generated
   */
  EClass getProtocols();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globaltype.globaljade.globalJade.Protocols#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Protocols#getName()
   * @see #getProtocols()
   * @generated
   */
  EAttribute getProtocols_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globaltype.globaljade.globalJade.Protocols#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Protocols#getRoles()
   * @see #getProtocols()
   * @generated
   */
  EReference getProtocols_Roles();

  /**
   * Returns the meta object for class '{@link org.xtext.globaltype.globaljade.globalJade.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globaltype.globaljade.globalJade.Role#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see org.xtext.globaltype.globaljade.globalJade.Role#getRole()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_Role();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GlobalJadeFactory getGlobalJadeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.globaltype.globaljade.globalJade.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globaltype.globaljade.globalJade.impl.ModelImpl
     * @see org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Protocols</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROTOCOLS = eINSTANCE.getModel_Protocols();

    /**
     * The meta object literal for the '{@link org.xtext.globaltype.globaljade.globalJade.impl.ProtocolsImpl <em>Protocols</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globaltype.globaljade.globalJade.impl.ProtocolsImpl
     * @see org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl#getProtocols()
     * @generated
     */
    EClass PROTOCOLS = eINSTANCE.getProtocols();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROTOCOLS__NAME = eINSTANCE.getProtocols_Name();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROTOCOLS__ROLES = eINSTANCE.getProtocols_Roles();

    /**
     * The meta object literal for the '{@link org.xtext.globaltype.globaljade.globalJade.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globaltype.globaljade.globalJade.impl.RoleImpl
     * @see org.xtext.globaltype.globaljade.globalJade.impl.GlobalJadePackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__ROLE = eINSTANCE.getRole_Role();

  }

} //GlobalJadePackage
