/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getContent <em>Content</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getRoleA <em>Role A</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getRoleB <em>Role B</em>}</li>
 * </ul>
 *
 * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage()
 * @model
 * @generated
 */
public interface Message extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute list.
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_Content()
   * @model unique="false"
   * @generated
   */
  EList<String> getContent();

  /**
   * Returns the value of the '<em><b>Role A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role A</em>' attribute.
   * @see #setRoleA(String)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_RoleA()
   * @model
   * @generated
   */
  String getRoleA();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getRoleA <em>Role A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role A</em>' attribute.
   * @see #getRoleA()
   * @generated
   */
  void setRoleA(String value);

  /**
   * Returns the value of the '<em><b>Role B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role B</em>' attribute.
   * @see #setRoleB(String)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_RoleB()
   * @model
   * @generated
   */
  String getRoleB();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getRoleB <em>Role B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role B</em>' attribute.
   * @see #getRoleB()
   * @generated
   */
  void setRoleB(String value);

} // Message
