/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getPayload <em>Payload</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getSender <em>Sender</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.Message#getReceiver <em>Receiver</em>}</li>
 * </ul>
 *
 * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage()
 * @model
 * @generated
 */
public interface Message extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Payload</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payload</em>' containment reference.
   * @see #setPayload(Payload)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_Payload()
   * @model containment="true"
   * @generated
   */
  Payload getPayload();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getPayload <em>Payload</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payload</em>' containment reference.
   * @see #getPayload()
   * @generated
   */
  void setPayload(Payload value);

  /**
   * Returns the value of the '<em><b>Sender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sender</em>' attribute.
   * @see #setSender(String)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_Sender()
   * @model
   * @generated
   */
  String getSender();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getSender <em>Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sender</em>' attribute.
   * @see #getSender()
   * @generated
   */
  void setSender(String value);

  /**
   * Returns the value of the '<em><b>Receiver</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' attribute.
   * @see #setReceiver(String)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMessage_Receiver()
   * @model
   * @generated
   */
  String getReceiver();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.Message#getReceiver <em>Receiver</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver</em>' attribute.
   * @see #getReceiver()
   * @generated
   */
  void setReceiver(String value);

} // Message
