/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiple Role</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.MultipleRole#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMultipleRole()
 * @model
 * @generated
 */
public interface MultipleRole extends Role
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(OneRole)
   * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getMultipleRole_Ref()
   * @model
   * @generated
   */
  OneRole getRef();

  /**
   * Sets the value of the '{@link org.xtext.globaltype.globaljade.globalJade.MultipleRole#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(OneRole value);

} // MultipleRole
