/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>One Role</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage#getOneRole()
 * @model
 * @generated
 */
public interface OneRole extends Role
{
} // OneRole
