/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.globaltype.globaljade.globalJade.Choice_rule;
import org.xtext.globaltype.globaljade.globalJade.End_message;
import org.xtext.globaltype.globaljade.globalJade.For_loop;
import org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage;
import org.xtext.globaltype.globaljade.globalJade.Message;
import org.xtext.globaltype.globaljade.globalJade.Model;
import org.xtext.globaltype.globaljade.globalJade.Protocol;
import org.xtext.globaltype.globaljade.globalJade.Role;
import org.xtext.globaltype.globaljade.services.GlobalJadeGrammarAccess;

@SuppressWarnings("all")
public class GlobalJadeSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GlobalJadeGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GlobalJadePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GlobalJadePackage.CHOICE_RULE:
				sequence_Choice_rule(context, (Choice_rule) semanticObject); 
				return; 
			case GlobalJadePackage.END_MESSAGE:
				sequence_End_message(context, (End_message) semanticObject); 
				return; 
			case GlobalJadePackage.FOR_LOOP:
				sequence_For_loop(context, (For_loop) semanticObject); 
				return; 
			case GlobalJadePackage.MESSAGE:
				sequence_Message(context, (Message) semanticObject); 
				return; 
			case GlobalJadePackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case GlobalJadePackage.PROTOCOL:
				sequence_Protocol(context, (Protocol) semanticObject); 
				return; 
			case GlobalJadePackage.ROLE:
				sequence_Role(context, (Role) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Choice_rule returns Choice_rule
	 *
	 * Constraint:
	 *     (role_name=GENERAL_NAME messages+=Message* messages+=Message*)
	 * </pre>
	 */
	protected void sequence_Choice_rule(ISerializationContext context, Choice_rule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     End_message returns End_message
	 *
	 * Constraint:
	 *     end+=END_MEX
	 * </pre>
	 */
	protected void sequence_End_message(ISerializationContext context, End_message semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     For_loop returns For_loop
	 *
	 * Constraint:
	 *     (name=GENERAL_NAME role=GENERAL_NAME messages+=Message*)
	 * </pre>
	 */
	protected void sequence_For_loop(ISerializationContext context, For_loop semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Message returns Message
	 *
	 * Constraint:
	 *     (type=TYPE_MESSAGE content+=CONTENT content+=CONTENT* roleA=GENERAL_NAME roleB=GENERAL_NAME)
	 * </pre>
	 */
	protected void sequence_Message(ISerializationContext context, Message semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (name=GENERAL_NAME roles+=Role roles+=Role* protocol+=Protocol)
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Protocol returns Protocol
	 *
	 * Constraint:
	 *     (actions+=Message | actions+=Choice_rule | actions+=For_loop | actions+=End_message)*
	 * </pre>
	 */
	protected void sequence_Protocol(ISerializationContext context, Protocol semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Role returns Role
	 *
	 * Constraint:
	 *     role=GENERAL_NAME
	 * </pre>
	 */
	protected void sequence_Role(ISerializationContext context, Role semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GlobalJadePackage.Literals.ROLE__ROLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GlobalJadePackage.Literals.ROLE__ROLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRoleAccess().getRoleGENERAL_NAMETerminalRuleCall_1_0(), semanticObject.getRole());
		feeder.finish();
	}
	
	
}
