/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.globaltype.globaljade.globalJade.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GlobalJadeFactoryImpl extends EFactoryImpl implements GlobalJadeFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GlobalJadeFactory init()
  {
    try
    {
      GlobalJadeFactory theGlobalJadeFactory = (GlobalJadeFactory)EPackage.Registry.INSTANCE.getEFactory(GlobalJadePackage.eNS_URI);
      if (theGlobalJadeFactory != null)
      {
        return theGlobalJadeFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GlobalJadeFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GlobalJadeFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GlobalJadePackage.MODEL: return createModel();
      case GlobalJadePackage.ROLES: return createRoles();
      case GlobalJadePackage.ROLE: return createRole();
      case GlobalJadePackage.ROLE_ONE: return createRoleOne();
      case GlobalJadePackage.ROLE_MULTIPLE: return createRoleMultiple();
      case GlobalJadePackage.PROTOCOL: return createProtocol();
      case GlobalJadePackage.RECURSION: return createRecursion();
      case GlobalJadePackage.CLOSE_RECURSION: return createCloseRecursion();
      case GlobalJadePackage.CHOICE: return createChoice();
      case GlobalJadePackage.FOR_EACH: return createForEach();
      case GlobalJadePackage.MESSAGE: return createMessage();
      case GlobalJadePackage.PAYLOAD: return createPayload();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Roles createRoles()
  {
    RolesImpl roles = new RolesImpl();
    return roles;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Role createRole()
  {
    RoleImpl role = new RoleImpl();
    return role;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RoleOne createRoleOne()
  {
    RoleOneImpl roleOne = new RoleOneImpl();
    return roleOne;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RoleMultiple createRoleMultiple()
  {
    RoleMultipleImpl roleMultiple = new RoleMultipleImpl();
    return roleMultiple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Protocol createProtocol()
  {
    ProtocolImpl protocol = new ProtocolImpl();
    return protocol;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Recursion createRecursion()
  {
    RecursionImpl recursion = new RecursionImpl();
    return recursion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CloseRecursion createCloseRecursion()
  {
    CloseRecursionImpl closeRecursion = new CloseRecursionImpl();
    return closeRecursion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Choice createChoice()
  {
    ChoiceImpl choice = new ChoiceImpl();
    return choice;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ForEach createForEach()
  {
    ForEachImpl forEach = new ForEachImpl();
    return forEach;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Message createMessage()
  {
    MessageImpl message = new MessageImpl();
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Payload createPayload()
  {
    PayloadImpl payload = new PayloadImpl();
    return payload;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GlobalJadePackage getGlobalJadePackage()
  {
    return (GlobalJadePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GlobalJadePackage getPackage()
  {
    return GlobalJadePackage.eINSTANCE;
  }

} //GlobalJadeFactoryImpl
