/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade.globalJade.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.globaltype.globaljade.globalJade.GlobalJadePackage;
import org.xtext.globaltype.globaljade.globalJade.Global_message;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Global message</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.impl.Global_messageImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.impl.Global_messageImpl#getRoleA <em>Role A</em>}</li>
 *   <li>{@link org.xtext.globaltype.globaljade.globalJade.impl.Global_messageImpl#getRoleB <em>Role B</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Global_messageImpl extends MinimalEObjectImpl.Container implements Global_message
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getRoleA() <em>Role A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleA()
   * @generated
   * @ordered
   */
  protected static final String ROLE_A_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRoleA() <em>Role A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleA()
   * @generated
   * @ordered
   */
  protected String roleA = ROLE_A_EDEFAULT;

  /**
   * The default value of the '{@link #getRoleB() <em>Role B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleB()
   * @generated
   * @ordered
   */
  protected static final String ROLE_B_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRoleB() <em>Role B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoleB()
   * @generated
   * @ordered
   */
  protected String roleB = ROLE_B_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Global_messageImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GlobalJadePackage.Literals.GLOBAL_MESSAGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GlobalJadePackage.GLOBAL_MESSAGE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRoleA()
  {
    return roleA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRoleA(String newRoleA)
  {
    String oldRoleA = roleA;
    roleA = newRoleA;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GlobalJadePackage.GLOBAL_MESSAGE__ROLE_A, oldRoleA, roleA));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRoleB()
  {
    return roleB;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRoleB(String newRoleB)
  {
    String oldRoleB = roleB;
    roleB = newRoleB;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GlobalJadePackage.GLOBAL_MESSAGE__ROLE_B, oldRoleB, roleB));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GlobalJadePackage.GLOBAL_MESSAGE__TYPE:
        return getType();
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_A:
        return getRoleA();
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_B:
        return getRoleB();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GlobalJadePackage.GLOBAL_MESSAGE__TYPE:
        setType((String)newValue);
        return;
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_A:
        setRoleA((String)newValue);
        return;
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_B:
        setRoleB((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GlobalJadePackage.GLOBAL_MESSAGE__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_A:
        setRoleA(ROLE_A_EDEFAULT);
        return;
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_B:
        setRoleB(ROLE_B_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GlobalJadePackage.GLOBAL_MESSAGE__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_A:
        return ROLE_A_EDEFAULT == null ? roleA != null : !ROLE_A_EDEFAULT.equals(roleA);
      case GlobalJadePackage.GLOBAL_MESSAGE__ROLE_B:
        return ROLE_B_EDEFAULT == null ? roleB != null : !ROLE_B_EDEFAULT.equals(roleB);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(", roleA: ");
    result.append(roleA);
    result.append(", roleB: ");
    result.append(roleB);
    result.append(')');
    return result.toString();
  }

} //Global_messageImpl
