/*
 * generated by Xtext 2.34.0
 */
package org.xtext.globaltype.globaljade;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GlobalJadeStandaloneSetup extends GlobalJadeStandaloneSetupGenerated {

	public static void doSetup() {
		new GlobalJadeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
